blog/urls.py
from django.urls import path, re_path

from blog import views
from blog.feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('list/', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/(?P<post>[-\w]+)/$', views.post_detail,
            name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('account.urls')),
    path("blog/", include('blog.urls', namespace='blog')),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from payment import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
from decimal import Decimal
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from mysite import settings
from orders.models import Order

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [],
        }
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    }
                },
                'quantity': item.quantity,
            })
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(name=order.coupon.code,
                                                 percent_off=order.discount,
                                                 duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}

{% block title %}
    결제 취소
{% endblock %}

{% block content %}
    <h1>결제가 처리되지 않았습니다</h1>
    <p>결제 처리 중에 문제가 발생했습니다.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends 'shop/base.html' %}

{% block title %}
	결제 완료
{% endblock %}

{% block content %}
	<h1>결제가 성공적으로 완료 되었습니다</h1>
    <p>결제가 성공적으로 처리되었습니다</p>
{% endblock %}

payment/templates/payment/process.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
    주문 결제
{% endblock %}

{% block content %}
    <h1>주문 요약</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>이미지</th>
            <th>상품</th>
            <th>가격</th>
            <th>수량</th>
            <th>총 가격</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>
                    <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                </td>
                <td>{{ item.product.name }}</td>
                <td class="num">${{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">${{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        {% if order.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="3"></td>
                <td class="num">
                    ${{ order.get_total_cost_before_discount|floatformat:2 }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ order.coupon.code }}" coupon
                    ({{ order.discount }}% off)
                </td>
                <td colspan="3"></td>
                <td class="num neg">
                    - ${{ order.get_discount|floatformat:2 }}
                </td>
            </tr>
        {% endif %}
        <tr>
            <td colspan="4">합계</td>
            <td class="num">${{ order.get_total_cost|floatformat:2 }}</td>
        </tr>
        </tbody>
    </table>
    <form action="{% url 'payment:process' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="지금 결제하기">
    </form>
{% endblock %}